Add kubectl with gavinbunney/kubectl as a required_providers
Otherwise the make aws script might fail at terraform init with the below error:
- Finding latest version of hashicorp/kubectl...
Error: Failed to install provider
Error while installing hashicorp/kubectl: provider registry
registry.terraform.io does not have a provider named
registry.terraform.io/hashicorp/kubectl